python main.py --method AlphaMixSampling --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method BADGE --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method corelog --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method coremse --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Coreset --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method CoresetCB --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method EntropyCB --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method LL --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method LFOSA --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method noise_stability --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Random --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method SAAL --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method TIDAL --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Uncertainty --uncertainty CONF --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Uncertainty --uncertainty Entropy --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Uncertainty --uncertainty Margin --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Uncertainty --uncertainty MeanSTD --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Uncertainty --uncertainty BALD --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
python main.py --method Uncertainty --uncertainty VarRatio --dataset CIFAR10 --trial 1 --cycle 3 --n-initial 500 --n-query 500 --n-class 10 --epochs 2 --n-drop 5 
